runtime: java11
env: standard
runtime_config:
  jdk: openjdk11
env_variables:
  SPRING_PROFILES_ACTIVE: "production"
handlers:
  - url: /.*
    script: this field is required, but ignored
instance_class: F2
inbound_services:
  - warmup
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  min_idle_instances: 5
  max_instances: 10000
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 30
